name: Test

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install our dependencies if we did not restore a dependency cache.
      # This will automatically install and cache dependencies for future runs.
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run linting
        run: yarn lint

      - name: Run tests with karma
        run: yarn test:cov

      - name: Upload coverage reports to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
